### ISSUE TITLE
VkNet.Exception.VkApiMethodInvokeException: "Client version deprecated"

### ISSUE THREAD

**Issue by rhiskey** [atckun/VkNetMusicBypass#20]
После авторизации метод  `api.Audio.Search` стал выдавать исключение  `"Client version deprecated"`
```csharp
    api.Authorize(new ApiAuthParams
    {
        Login ="799999999999",
        Password = "myVKpassword"
    });
```
```csharp
      var audios = api.Audio.Search(new AudioSearchParams
      {
          Autocomplete = false,
          Query = "Kino - Gruppa",
          Count = 1,
          SearchOwn = false,
          Sort = AudioSort.AddedDate
      });
```
{VkNet.Infrastructure.VkApiVersionManager}: VkApiVersion = 5.126
.net5.0
VkNet v.1.69.0
VkNet.AudioBypassService v.1.7.3

**Comment by BlizPerfect** [comment]
Тоже самое

На нашли решение?
Последний раз к коду притрагивался 3-4 месяца назад и всё было исправно.

**Comment by IronPythonDev** [comment]
> Тоже самое
> 
> На нашли решение? Последний раз к коду притрагивался 3-4 месяца назад и всё было исправно.

Это проблема VkNet у меня на VkNet(1.52.0) и VkNet.AudioBypassService(1.5.3) все работает правильно

**Comment by BlizPerfect** [comment]
> > Тоже самое
> > На нашли решение? Последний раз к коду притрагивался 3-4 месяца назад и всё было исправно.
> 
> Это проблема VkNet у меня на VkNet(1.52.0) и VkNet.AudioBypassService(1.5.3) все работает правильно

Спасибо за ответ!
Да, действительно, на VkNet(1.52.0) и VkNet.AudioBypassService(1.5.3) всё отлично!

**Comment by rhiskey** [comment]
> > Тоже самое
> > На нашли решение? Последний раз к коду притрагивался 3-4 месяца назад и всё было исправно.
> 
> Это проблема VkNet у меня на VkNet(1.52.0) и VkNet.AudioBypassService(1.5.3) все работает правильно

Топ, откатился до этих версий и все заработало, спасибо тебе!

**Comment by an9r0f** [comment]
Беру реализацию от сюда, поэтому на код не завязан, всё дело в том что раньше была реализация от kate а потом её переделали на офф клиент, с очень куцими полями, отдаётся не кашерный токен.
Откатить в текущей версии эти строки, проверено работает.
https://github.com/0xshelln1ght/VkNet.AudioBypass/commit/853820672745493068b84d116967126bc4b649c0#diff-21409458692cadbfc13184535ae234042e187c3124870ca8a2e63d7e4bec0726L100

в поле device должен быть androidId из предыдущего метода а не рандом на 22 знака

**Comment by teland94** [comment]
сейчас вот это пишет с версией VkNet.AudioBypassService v.1.7.3 при авторизации:
Method not found: 'System.Threading.Tasks.Task`1<VkNet.Utils.HttpResponse`1<System.String>> VkNet.Abstractions.Utils.IRestClient.PostAsync(System.Uri, System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<System.String,System.String>>, System.Text.Encoding)'.

**Comment by teland94** [comment]
А отправка сообщений не работает. API возращает id message, по факту я не вижу отправки.

**Comment by Pivigor** [comment]
У меня тоже не работает, тоже на этапе авторизации

```
Unhandled exception. System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<VkNet.Utils.HttpResponse`1<System.String>> VkNet.Abstractions.Utils.IRestClient.PostAsync(System.Uri, System.Collections.Generic.IEn
umerable`1<System.Collections.Generic.KeyValuePair`2<System.String,System.String>>, System.Text.Encoding)'.
   at VkNet.AudioBypassService.Utils.VkApiInvoker.InvokeAsyncInternal(Uri uri, IDictionary`2 parameters, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at VkNet.AudioBypassService.Utils.VkApiInvoker.InvokeAsyncInternal(Uri uri, IDictionary`2 parameters, CancellationToken cancellationToken)
   at VkNet.AudioBypassService.Utils.VkApiInvoker.<>c__DisplayClass5_0.<CallAsync>b__0(Nullable`1 sid, String key)
   at VkNet.Utils.CaptchaHandler.Perform[T](Func`3 action)
   at VkNet.AudioBypassService.Utils.VkApiInvoker.CallAsync(Uri uri, VkParameters parameters, CancellationToken cancellationToken)
   at VkNet.AudioBypassService.Utils.VkApiInvoker.CallAsync[T](Uri uri, VkParameters parameters, CancellationToken cancellationToken)
   at VkNet.AudioBypassService.VkAndroidAuthorization.BaseAuthAsync()
   at VkNet.AudioBypassService.VkAndroidAuthorization.AuthorizeAsync()
   at VkNet.VkApi.BaseAuthorize(IApiAuthParams authParams)
   at VkNet.VkApi.AuthorizeWithAntiCaptcha(IApiAuthParams authParams)
   at VkNet.VkApi.Authorize(IApiAuthParams params)
   at VkNet.VkApi.Authorize(ApiAuthParams params)
```

**Comment by itsokto** [comment]
> Беру реализацию от сюда, поэтому на код не завязан, всё дело в том что раньше была реализация от kate а потом её переделали на офф клиент, с очень куцими полями, отдаётся не кашерный токен. Откатить в текущей версии эти строки, проверено работает. [8538206#diff-21409458692cadbfc13184535ae234042e187c3124870ca8a2e63d7e4bec0726L100](https://github.com/0xshelln1ght/VkNet.AudioBypass/commit/853820672745493068b84d116967126bc4b649c0#diff-21409458692cadbfc13184535ae234042e187c3124870ca8a2e63d7e4bec0726L100)
> 
> в поле device должен быть androidId из предыдущего метода а не рандом на 22 знака

в kate не приходили обложки альбомов и треков. нужно снова проверить и возможно вернуть эти данные авторизации

**Comment by itsokto** [comment]
> сейчас вот это пишет с версией VkNet.AudioBypassService v.1.7.3 при авторизации: Method not found: 'System.Threading.Tasks.Task`1<VkNet.Utils.HttpResponse`1<System.String>> VkNet.Abstractions.Utils.IRestClient.PostAsync(System.Uri, System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<System.String,System.String>>, System.Text.Encoding)'.

исправлено в 1.7.4
