### ISSUE TITLE
PHONE_REGISTRATION_ERROR

### ISSUE THREAD

**Issue by IronPythonDev** [atckun/VkNetMusicBypass#24]
`
System.InvalidOperationException: GetReceipt bad response: PHONE_REGISTRATION_ERROR
System.Net.Http.FormUrlEncodedContent
   at VkNet.AudioBypassService.Utils.FakeSafetyNetClient.GetReceipt(AndroidCheckinResponse credentials)
   at VkNet.AudioBypassService.Utils.ReceiptParser.GetReceipt()
   at VkNet.AudioBypassService.Utils.VkAndroidAuthorization.AuthorizeAsync()
   at VkNet.VkApi.BaseAuthorize(IApiAuthParams authParams)
   at VkNet.VkApi.AuthorizeWithAntiCaptcha(IApiAuthParams authParams)
   at VkNet.VkApi.Authorize(IApiAuthParams params)
   at VkNet.VkApi.<>c__DisplayClass47_0.<AuthorizeAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at MusConv.Lib.VkMusic.VkMusicApi.AuthorizationAsync(IApiAuthParams authParams) in F:\musconv\musconv-avalonia\MusConv.Models\MusConv.Lib.VkMusic\VkMusicApi.cs:line 155
   at MusConv.Lib.VkMusic.VkMusicApi.AuthorizationAsync(String login, String password, String twoFactorCode) in F:\musconv\musconv-avalonia\MusConv.Models\MusConv.Lib.VkMusic\VkMusicApi.cs:line 102
   at MusConv.ViewModels.Models.MusicService.VKModel.AuthorizeCredAsync(String login, String password) in F:\musconv\musconv-avalonia\MusConv.ViewModels\Models\MusicService\VKModel.cs:line 36
   at MusConv.ViewModels.ViewModels.SectionViewModels.VKViewModel.AuthorizeWithLoginAndPassword(String login, String password) in F:\musconv\musconv-avalonia\MusConv.ViewModels\ViewModels\SectionViewModels\VKViewModel.cs:line 193
   at MusConv.ViewModels.ViewModels.SectionViewModels.VKViewModel.Web_NavigatingAsync(Object s, Object t) in F:\musconv\musconv-avalonia\MusConv.ViewModels\ViewModels\SectionViewModels\VKViewModel.cs:line 256a
`

**Comment by IronPythonDev** [comment]
System.InvalidOperationException: GetReceipt bad response: PHONE_REGISTRATION_ERROR
System.Net.Http.FormUrlEncodedContent
   at VkNet.AudioBypassService.Utils.FakeSafetyNetClient.GetReceipt(AndroidCheckinResponse credentials)
   at VkNet.AudioBypassService.Utils.ReceiptParser.GetReceipt()
   at VkNet.AudioBypassService.Utils.VkAndroidAuthorization.AuthorizeAsync()
   at VkNet.VkApi.BaseAuthorize(IApiAuthParams authParams)
   at VkNet.VkApi.AuthorizeWithAntiCaptcha(IApiAuthParams authParams)
   at VkNet.VkApi.Authorize(IApiAuthParams params)
   at VkNet.VkApi.<>c__DisplayClass47_0.<AuthorizeAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at MusConv.Lib.VkMusic.VkMusicApi.AuthorizationAsync(IApiAuthParams authParams) in F:\musconv\musconv-avalonia\MusConv.Models\MusConv.Lib.VkMusic\VkMusicApi.cs:line 155
   at MusConv.Lib.VkMusic.VkMusicApi.AuthorizationAsync(String login, String password, String twoFactorCode) in F:\musconv\musconv-avalonia\MusConv.Models\MusConv.Lib.VkMusic\VkMusicApi.cs:line 102
   at MusConv.ViewModels.Models.MusicService.VKModel.AuthorizeCredAsync(String login, String password) in F:\musconv\musconv-avalonia\MusConv.ViewModels\Models\MusicService\VKModel.cs:line 36
   at MusConv.ViewModels.ViewModels.SectionViewModels.VKViewModel.AuthorizeWithLoginAndPassword(String login, String password) in F:\musconv\musconv-avalonia\MusConv.ViewModels\ViewModels\SectionViewModels\VKViewModel.cs:line 193
   at MusConv.ViewModels.ViewModels.SectionViewModels.VKViewModel.Web_NavigatingAsync(Object s, Object t) in F:\musconv\musconv-avalonia\MusConv.ViewModels\ViewModels\SectionViewModels\VKViewModel.cs:line 256a

**Comment by ghost** [comment]
Ошибка возникает редко. Скорее всего защита от частого вызова этого метода со стороны гугла.

**Comment by Fariarx** [comment]
Ошибка связана с асинхронным AuthorizeAsync. С синхронным такой проблемы нет.
